### ISSUE TITLE
Import button not available

### ISSUE THREAD

**Issue by Chifuyu** [olga-jane/prizm#1478] opened 2015-02-18 10:11 UTC
if i choose not a file but click button input then i can`t click on it again.

File -> Import
click Import button
then i choose a file and i can`t click again on input
Хоменко

**Comment by kapcia** [comment] 2015-02-18 16:04
Duplicate of issue: Deactivated button on import #1448

**Comment by kapcia** [comment] 2015-02-19 08:38
Cannot reproduce in 1.0.32.1

**Closed** 2015-02-19 08:42 UTC
Labels: bug, bug - functional, bug - UI, Coding, DUPLICATE, Export/Import, MEDIUM priority
