### ISSUE TITLE
Restrictions not loaded by default

### ISSUE THREAD

**Issue by demmy** [olga-jane/prizm#978] opened 2015-01-21 16:08 UTC
1. open settings -> roles
**restrictions checkboxes emty**
2. switch user by click and back to administrator
**restrictions checkboxes filled**

**Comment by kapcia** [comment] 2015-01-22 08:44
Cannot reproduce

**Comment by olga-jane** [comment] 2015-02-24 22:11
seems to be fixed by other task

**Closed by olga-jane** 2015-02-24 22:11 UTC
Labels: bug, bug - functional, bug - UI, Coding, MEDIUM priority, Settings
